name: Build and release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: yarn install
      - run: yarn --frozen-lockfile
      - run: npm install --global pkg
      - name: Build
        run: pkg . --output subathon-timer --targets win
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            subathon-timer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}